server:
  port: 8080

spring:


  datasource:
    url: jdbc:mysql://localhost:3306/odcdev?serverTimezone=Asia/Seoul
    username: root
    password: 7729
    driver-class-name: com.mysql.cj.jdbc.Driver

      
  redis:
    data:
      host: localhost
      port: 6379
      timeout: 5000 
  mail:
    host: smtp.gmail.com 
    port: 587
    #port: 465
    username: ks67606561@gmail.com
    password: suyvjjxffhbwjoil
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
mybatis:
  mapper-locations: classpath:com/odc/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
   # mapUnderscoreToCamelCase: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # typeAliasesPackage: com.odc.**.dto
logging:
  level:
    root: DEBUG
    org.springframework.web: DEBUG
    org.mybatis: DEBUG
    com.odc: DEBUG
app:
  views:
    url: http://localhost:8080
    port: 8080