server:
  port: 8080

spring:


  datasource:
    url: jdbc:mysql://localhost:3306/odcdev?serverTimezone=Asia/Seoul
    username: root
    password: 7729
    driver-class-name: com.mysql.cj.jdbc.Driver

      
  redis:
    data:
      host: localhost
      port: 6379
      timeout: 5000 
  mail:
    host: smtp.gmail.com 
    port: 587
    #port: 465
    username: ks67606561@gmail.com
    password: suyvjjxffhbwjoil
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: my-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        spring.json.encoding: UTF-8
mybatis:
  mapper-locations: classpath:com/odc/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
   # mapUnderscoreToCamelCase: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # typeAliasesPackage: com.odc.**.dto
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.mybatis: INFO
    com.odc: INFO
app:
  views:
    url: http://localhost:8080
    port: 8080